### PR TITLE
fixing 404 issue in beta test failure

### PR DESCRIPTION
**Pull request by shivam-g**

### CODE REVIEW

**Comment by shivam-g** [comment]
cc @asati

**Comment by asati** [comment]
@MiguelMadero @zen-mde For micro-services, api end points will start with`/internal-service/` (as they getting proxied for a prefix of url to make sure we only open certain urls to public), so we need to whitelist them to make Glue test work properly. 

Can you please help us reveiw and deploy this change.

**Comment by MiguelMadero** [comment]
I'm not super familiar with this part of testem and glue, but this LGTM

**Comment by z-mkorystov** [comment]
Looks good

**Pull request merged**
